export const types = {
    CHANGE_TITLE: "CHANGE_TITLE",
    WITH_PARAMS: "WITH_PARAMS",
    VALUE: "VALUE",
    ADD_USER: "ADD_USER",
    DELETE_ALL: "DELETE_ALL",
    SUM_INPUT: "SUM_INPUT",
    LIST_SUMS: "LIST_SUMS",
    CLEAR: "CLEAR"
}